### ISSUE TITLE
mod_passenger restart

### ISSUE THREAD

**Issue by waynegraham** [uvalib/geoblacklight#3]
With the `passenger` tasks enabled (see [project](https://github.com/capistrano/passenger/)), an SSHKit exception is thrown executing the process (`sudo passenger-config restart-app`) even if the flag to restart passenger with `sudo` is enabled in the `deploy.rb` file:

```
set :passenger_restart_with_sudo, true
```

Need to track down if this is an OS issue or a `capistrano` issue.

**Comment by ammonshepherd** [comment]
This may have been an OS issue which was solved by explicitly setting the umask for each user and in the system files to `umask 002` so that files/directories will inherit group permissions (664/775).
